
# cargo-vet config file

[cargo-vet]
version = "0.9"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.addr2line]]
version = "0.21.0"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.arrayvec]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.askama]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.askama_derive]]
version = "0.12.5"
criteria = "safe-to-deploy"

[[exemptions.askama_escape]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.askama_parser]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.22.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.97"
criteria = "safe-to-deploy"

[[exemptions.deunicode]]
version = "1.6.0"
criteria = "safe-to-run"

[[exemptions.errno]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.fake]]
version = "2.9.2"
criteria = "safe-to-run"

[[exemptions.fastrand]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.28.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.humansize]]
version = "2.1.3"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.9.0"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.21"
criteria = "safe-to-deploy"

[[exemptions.mime_guess]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.num-format]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.32.2"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.openssl]]
version = "0.10.64"
criteria = "safe-to-deploy"

[[exemptions.openssl-sys]]
version = "0.9.102"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.5"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.5"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.4.0"
criteria = "safe-to-run"

[[exemptions.quick-error]]
version = "1.2.3"
criteria = "safe-to-run"

[[exemptions.rand_xorshift]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.redox_syscall]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "2.1.2"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.7.0"
criteria = "safe-to-deploy"

[[exemptions.rusty-fork]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.schannel]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.2"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.system-configuration]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.system-configuration-sys]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.10.1"
criteria = "safe-to-deploy"

[[exemptions.tinyvec_macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.tower]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.40"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.32"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen]]
version = "0.2.92"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.48.5"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.5"
criteria = "safe-to-deploy"

[[exemptions.winreg]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.34"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.34"
criteria = "safe-to-deploy"
